[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "youtube_comment_intelligence_system"
version = "0.2.0"
description = "YouTube commments analysis by BERT-transformer, BERTopic, and RAG"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client",
    "google-auth",
    "pandas",
    "datasets",
    "torch",
    "optimum[onnxruntime]>=1.16.0",
    "dotenv",
    "langchain-huggingface",
    "sentence-transformers",
    "lingua-language-detector",
    "hdbscan",
    "bertopic",
    "nbformat",
    
]

[project.optional-dependencies]
dev = [
    "langdetect",
    "ipykernel",
    "fasttext",
]

# uv CPU PyTorch stroage setting
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[tool.setuptools.packages.find]
where = ["src"]
